//variables

let producto = 'audifonos Gamer'; /* Iniciar variable y asignar un valor */

let disponible; /* Iniciar la variable sin ninguna valor */

producto = true; /* Reasignando el valor de la variable */

disponible = true;

let producto1 = 'Computadora',
    disponible1 = true,
    categoria = 'computadoras';

// let 1disponible;
let disponible__;

/* Estilos para las variables */
console.warn('Estilos para las variables');

let nombre_producto = 'Monitor HD'; // Underscasre
let nombreProducto = 'Monitor HD'; // CamelCase
let NombreProducto = 'Monitor HD'; // Pascal Case
let nombreproducto = 'Monitor HD';

console.log();
